# Generated by Django 6.0.1 on 2026-02-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='car_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='mileage',
            field=models.IntegerField(default=0),
        ),
    ]
