# Generated by Django 6.0.1 on 2026-02-16 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_car_model_question_mileage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
